### ISSUE TITLE
Model Validation does not accept rules with parameters

### ISSUE THREAD

**Issue by Deputaats** [zombor/Auto-Modeler#1]
Should accept rules defined like this:

protected $_rules = array(

```
              'field_name' => array
              (
                  'not_empty'   => NULL,
                  'max_length'  => array(32),
              ),
```

);

Possible solution:
automodeler.php
Lines: 164 and 165

From:
foreach ($rule as $sub_rule)
$data->rule($field, $sub_rule);

To:
foreach ($rule as $sub_rule => $sub_value)
$data->rule($field, $sub_rule, $sub_value);

Or maybe switch to $data->rules() function...

**Comment by zombor** [comment]
This has been fixed in the develop branch, by moving to Validation::rules().
