### ISSUE TITLE
find_related method bug in version 3.3

### ISSUE THREAD

**Issue by Gazoo** [zombor/Auto-Modeler#12]
On line 111 please change :
    $query = db::select(AutoModeler::factory(inflector::singular($key))->fields())->from($key)->order_by($order_by, $order);

To:
    $query = db::select_array(AutoModeler::factory(inflector::singular($key))->fields())->from($key)->order_by($order_by, $order);

KO3 db::select() does not support passing in arrays so we should be using db::select_array() instead

**Comment by zombor** [comment]
This is already fixed in the develop branch.
