### ISSUE TITLE
Set message and error defaults for AutoModeler Exception handler

### ISSUE THREAD

**Issue by Gazoo** [zombor/Auto-Modeler#15]
Can we change the AutoModeler exception handler __construct() on line 377 from:
    public function __construct($title, $message, $errors)
to
    public function __construct($title, $message=array(), $errors='')

That way we don't always have to pass in empty arrays or empty strings when throwing AutoModeler exceptions. Current Eg from automodeler code:
    throw new AutoModeler_Exception('Field '.$key.' does not exist in '.get_class($this).'!', array(), '');
to:
    throw new AutoModeler_Exception('Field '.$key.' does not exist in '.get_class($this).'!');

**Comment by zombor** [comment]
Fixed by https://github.com/zombor/Auto-Modeler/commit/5390273531f8b42ba2ef1c0813ccaff9c614c484
