### ISSUE TITLE
Crash on iterate after upgrading from 3.5 -> 3.6

### ISSUE THREAD

**Issue by rafi** [zombor/Auto-Modeler#16]
Simple:
    $categories = AutoModeler::factory('category')->fetch_all();
    foreach ($categories as $category)    // Error triggered here
    {
        echo Kohana::debug($category);
    }

Yields:
    Exception [ 0 ]: Could not execute Model_Category::__construct()
After upgrading from 3.5 -> 3.6

**Comment by zombor** [comment]
It looks like there's an exception being thrown in the constructor. Odd that all the tests passed. Can you gist or pastebin your Model_Category class?

One thing to try is to wrap the code in the constructor in a try/catch, and do:

  die($e->getMessage());

In the catch block.

**Comment by rafi** [comment]
http://pastebin.com/eVZsaeJv

**Comment by rafi** [comment]
Found the problem. Forgot to add 'parent_id' to model $_data
everything works fine now. Its weird though.. The try/catch didn't help either...

**Comment by zombor** [comment]
Yeah, that was a "problem" with previous versions, not sure why you wouldn't have experienced it with 3.5.

**Comment by rafi** [comment]
Looks like the query is now "SELECT *" and on 3.5 it was "SELECT [$_data fields]"

**Comment by zombor** [comment]
Hrm, it should be selecting each data field individually. Can you file a new bug report for this? Please include sample code. :)

**Comment by zombor** [comment]
See #16.

**Comment by rafi** [comment]
You meant #17
