### ISSUE TITLE
load method bug

### ISSUE THREAD

**Issue by mattias** [zombor/Auto-Modeler#19]
Bug can be seen in vendo. __set hashes the password field there.
Since load makes use of __set, the password from the database will get hashed even though it's already hashed.

Having password field being hashed in __set has some value. And changing load to set the fields in _data directly might not be wanted.

Model States implementation? ^.^

**Comment by zombor** [comment]
add tests for model states, closed by fe7a4dc6bf4761f10401b5cafa19bc013d2a975d
