### ISSUE TITLE
_state = 'new' when loading multiple results with load()

### ISSUE THREAD

**Issue by anqqa** [zombor/Auto-Modeler#23]
Both in develop and feature/kohana-3.1 branches using $model->load($query, null) returns models with STATE_NEW instead of STATE_LOADED causing AutoModeler to attempt to insert new records instead of updating old when updating any of the resulted models.

**Comment by zombor** [comment]
Models loaded with load(*, NULL) should result in loaded state, closed by 77caccaf9b396bfa2bc5e01676f90db3141239f6
