### ISSUE TITLE
conflict with Database and Auto-Modeler

### ISSUE THREAD

**Issue by mattias** [zombor/Auto-Modeler#24]
Strict Standards: Declaration of Database_Query_Builder_Select::select_array() should be compatible with that of Kohana_Database_Query_Builder_Select::select_array() in .../modules/auto-modeler/classes/database/query/builder/select.php on line 11

It seems the Database module has changed and now has only one param in that method while the Auto-Modeler one has two.

**Comment by zombor** [comment]
Turning off strict checking will remove this error. Strict checking generally isn't needed anyway.
