### ISSUE TITLE
Column 'id' in field list is ambiguous

### ISSUE THREAD

**Issue by nanodocumet** [zombor/Auto-Modeler#26]
When using _load_with, the __construct method at the line below:

https://github.com/zombor/Auto-Modeler/blob/feature%2Fkohana-3.1/classes/automodeler/core.php#L57

instead of:

```
$this->load(db::select_array(array_keys($this->_data))->where($this->_table_name.'.id', '=', $id));
```

should be

```
$this->load(db::select_array($this->fields())->where($this->_table_name.'.id', '=', $id));
```

otherwise it throws the error of Column 'id' is ambiguos. ($this->fields() takes care of adding the table name accordingly)

Note:
This commit https://github.com/zombor/Auto-Modeler/commit/65f56b53ff1bc04e8483cf3a1b02727eb12890c3 helped a little bit, but still didn't solve the problem.

**Comment by zombor** [comment]
Fix ambiguous column error when using with(). Closed by ebb104941e01cf0903b5fcf6b531fc61fc33a5fb
