### ISSUE TITLE
set_fields() 

### ISSUE THREAD

**Issue by iammerrick** [zombor/Auto-Modeler#27]
In the comments and auto-generated documentation it directs to always use something like array_key_intersect but it seems this is now being done in the method itself. Am I way off here? Should the comment/docs not be updated?

```
    public function set_fields(array $data)
{
    foreach (array_intersect_key($data, $this->_data) as $key => $value)
    {
        $this->$key = $value;
    }
}
```

**Comment by zombor** [comment]
This is actually invalid. You should also use something like Arr::extract() to pass in desired fields. This way you don't end up passing things like `id` which is almost never wanted.

**Comment by iammerrick** [comment]
Yeah as per what we discussed. Thank you.

**Comment by iammerrick** [comment]
Is it worth doing the two arguments like ORM? $_POST, array('what', 'i', 'want')? I would be happy to implement.
