### ISSUE TITLE
fetch_all (and probably fetch_where) causes exception Could not execute __construct()

### ISSUE THREAD

**Issue by slacker** [zombor/Auto-Modeler#3]
If $_data does not contain 'id', exception is thrown while attempting to iterate over the result.

Changing

```
return db::select('*')
```

to

```
return db::select(array_keys($this->_data))
```

prevents the exception.

**Comment by zombor** [comment]
Select using field arrays instead of *. Closed by b127204a465699cf18faa433a2f826f3a01d5946.
