### ISSUE TITLE
array_key_exists instead of isset

### ISSUE THREAD

**Issue by zsoerenm** [zombor/Auto-Modeler#38]
https://github.com/zombor/Auto-Modeler/blob/master/classes/automodeler/orm/core.php#L27

should be

```
if(array_key_exists($key.'_id',$this->_data))
```

For better debugging:
    isset() does not return TRUE for array keys that correspond to a NULL value, while array_key_exists() does. 

http://php.net/manual/en/function.array-key-exists.php

**Comment by zsoerenm** [comment]
actually that's rubish...

no id -> no model

sry

**Comment by zombor** [comment]
Right, I'm using array_key_exists() inside automodeler/core.php's set/get :)
