### ISSUE TITLE
Auth_AutoModeler_ORM passes username to constructor

### ISSUE THREAD

**Issue by Crotalus** [zombor/Auto-Modeler#40]
Seems like Auth_AutoModeler_ORM::_login() passes $username instead of $id to constructor.

// Load the user
$user = new Model_User($username);

should be something like
$user = Model::factory('user')->load(DB::select()->where('username', '=', $username))....

or maybe even better, some comparision of lower(username) = lower('$username') so it's case insensitive?

**Comment by zombor** [comment]
It assumes you have some sort of overloaded constructor to load your user by whatever your "username" field you are logging the user in as. It doesn't enforce any kind of convention. It could be an email address, username, etc.
