### ISSUE TITLE
AutoModeler $_has_many and with()

### ISSUE THREAD

**Issue by danieliser** [zombor/Auto-Modeler#47]
Have a clients table with a 1 to many relationship with a notes table. Trying to get them linked with AM and getting,

ErrorException [ Notice ]: Undefined variable: fields

<code>MODPATH\automodeler\classes\automodeler\core.php [ 490 ]
485     public function fields()
486     {
487         foreach ($this->_data as $key => $value)
488             $fields[] = $this->_table_name.'.'.$key;
489 
490         return $fields;
491     }
492 
493     /**
494      \* Returns if the specified field exists in the model
495      *</code>

Here is my code.

<code>$id = $this->request->param('id');
$values = new Model_Client();
$values->with('notes')->load(db::select()->where('clients.id', '=', $id));</code>

Models are

<code>class Model_Client extends AutoModeler_ORM
{
    protected $_table_name  = 'clients';
    protected $_has_many = array('notes');
    protected $data = array(
        'id' => '',
        'firstname' => '',
        'lastname' => '',
        'email' => '',
        'primaryphone' => '',
        'phonehome' => '',
        'phonework' => '',
        'phonemobile' => '',
        'birthmonth' => '',
        'birthday' => '',
        'address' => '',
        'city' => '',
        'state' => '',
        'zipcode' => '',
        'employee_id' => '',
        'created' => '',
        'created_by' => '',
        'updated' => '',
        'updated_by' => ''
    );
}
class Model_Note extends AutoModeler_ORM
{
    protected $_table_name  = 'notes';
    protected $_belongs_to = array('clients');
    protected $data = array(
        'id' => '',
        'client_id' => '',
        'type' => '',
        'date' => '',
        'content' => '',
        'created' => '',
        'updated' => ''
    );
    protected $rules = array(
        'type' => array('not_empty'),
        'content' => array('not_empty')
    );
}</code>

**Comment by zombor** [comment]
Your model should be $_data.
