### ISSUE TITLE
ORM database result models do not get upper-cased properly

### ISSUE THREAD

**Issue by Gazoo** [zombor/Auto-Modeler#5]
In Auto_Modeler_ORM the database result models returned are not upper-cased as intended. This is because the `inflector`:

```
inflector::singular(ucwords($key);
```

To fix just change the order to make sure that `ucwords` is run after the `inflector`

```
ucwords(inflector::singular($key));
```

**Comment by zombor** [comment]
Fixed in a37c0f3a136919b2010cfd7d560651ca177f7221
