### ISSUE TITLE
should Automodeler_ORM_Core's __get method throw an exception?

### ISSUE THREAD

**Issue by nanodocumet** [zombor/Auto-Modeler#51]
Automodeler_Core does it here:

https://github.com/zombor/Auto-Modeler/blob/master/classes/automodeler/core.php#L181

Automodeler_ORM_Core does not:

https://github.com/zombor/Auto-Modeler/blob/master/classes/automodeler/orm/core.php#L28

Is that the intended behavior?

Thanks,

Nano.

**Comment by zombor** [comment]
Line 44 should probably use `parent::__get()`
