### ISSUE TITLE
Auto Modeler tries to make a field singular that is already singular

### ISSUE THREAD

**Issue by rjd22** [zombor/Auto-Modeler#6]
<?php echo $anime->airing_status->status; ?> <-- it tries to deletes 'S' at the end of airing_status.

fix:
automodeler/orm.php line 28
change:
as_object('Model_'.ucwords(inflector::singular($key)))
to:
as_object('Model_'.ucwords($key))

**Comment by zombor** [comment]
__get() does not need to perform singular transformation, closed by bcf623a95a526a43ab061897034a356f27115bd6
